<?php
if(!defined('InEmpireCMS'))
{
	exit();
}
define('EmpireCMSDPConfig',TRUE);
$mob_r=array();
//dp.config.data
$mob_r['mob_open']=1;
$mob_r['msitepath']='/www/wwwroot/www.copyeoe.com/m/';
$mob_r['msiteurl']='http://eoem.xz59.com/';
$mob_r['newsurl']='http://eoe.xz59.com/';
$mob_r['gid']=2;
$mob_r['ltp']=1;
$mob_r['zkey']=1;
$mob_r['zpic']=1;
$mob_r['zpicsize']=320;
//dp.config.data
//dp.class.data
//dp.class.data
?>